services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: bn_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bn_postgres:/var/lib/postgresql/data
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - bn_redis:/data
volumes:
  bn_postgres:
  bn_redis:
